/**
 * Mail Utility Functions
 * Handles all email sending operations
 */

const axios = require('axios');
require('dotenv').config();

const emailServiceUrl = process.env.EMAIL_SERVICE_URL || 'https://email-service-delta-seven.vercel.app/api/send-email';

const sendMail = async ({ to, subject, html}) => {
    if (!process.env.EMAIL_SERVICE_API) {
        throw new Error('EMAIL_SERVICE_API is required');
    }
    if (!process.env.EMAIL) {
        throw new Error('EMAIL is required as the sender address');
    }

    await axios.post(emailServiceUrl, {
        from: process.env.EMAIL,
        to,
        subject,
        html
    }, {
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${process.env.EMAIL_SERVICE_API}`
        }
    });
};

/**
 * Send OTP Email
 * @param {string} emailId - Recipient email address
 * @param {number} otp - One Time Password
 * @param {string} username - User's name
 * @param {string} purpose - Purpose of OTP (e.g., "Password Reset", "Email Verification")
 */
const sendOTPEmail = async (emailId, otp, username, purpose = "Verification") => {
    try {
        await sendMail({
            to: emailId,
            subject: `Your OTP for ${purpose}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 20px; border-radius: 8px; background-color: #f9f9f9; border: 1px solid #ddd;">
                    <div style="text-align: center; background-color: #030711; padding: 15px; border-radius: 8px 8px 0 0;">
                        <img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%2024%2C%202026%2C%2011_11_38%20PM-G7W8fRrfMM3iBOkWdjTTdkKmT4nXVX.png" alt="Triptual Logo" style="max-width: 80px;">
                        <h2 style="color: #ffffff; margin: 10px 0;">OTP Verification</h2>
                    </div>
                    <div style="background-color: #ffffff; padding: 20px; border-radius: 0 0 8px 8px; text-align: center;">
                        <p style="font-size: 16px;">Dear <strong>${username}</strong>,</p>
                        <p>Your OTP for <strong>${purpose}</strong> is:</p>
                        <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin-top: 10px; text-align: center;">
                            <h2 style="color: #030711; font-size: 24px; margin: 0;">${otp}</h2>
                            <p style="margin-top: 5px; color: red;">This OTP expires in 5 minutes.</p>
                        </div>
                        <p style="text-align: center; color: gray; font-size: 12px; margin-top: 20px;">
                            If you did not request this OTP, please ignore this email.<br>
                            Thank you, <br>Triptual Team
                        </p>
                    </div>
                    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
                    <p style="color:gray; font-size:12px; text-align: center;">This is an autogenerated message. Please do not reply to this email.</p>
                </div>
            `,
            text: `Dear ${username},\n\nYour OTP for ${purpose} is: ${otp}\n\nThis OTP expires in 5 minutes.`
        });
        return { success: true, message: "Email sent successfully" };
    } catch (error) {
        console.error("Mail Error:", error.response?.data || error.message);
        throw error;
    }
};

/**
 * Send Generic Email
 * @param {string} emailId - Recipient email address
 * @param {string} subject - Email subject
 * @param {string} htmlContent - Email body in HTML format
 */
const sendEmail = async (emailId, subject, htmlContent) => {
    try {
        await sendMail({
            to: emailId,
            subject,
            html: htmlContent
        });
        return { success: true, message: "Email sent successfully" };
    } catch (error) {
        console.error("Mail Error:", error.response?.data || error.message);
        throw error;
    }
};

module.exports = {
    sendOTPEmail,
    sendEmail
};
